bases:
- helmfiles/envs/environment.yaml

repositories:
- name: gdp
  url: https://referentiel-livraison.devops.prod.fdj.fr/repository/gdp-helm-releases/

helmDefaults:
  skipDeps: true
  wait: true
  historyMax: 5
helmBinary: /usr/local/bin/helm3
# these labels will be applied to all releases in a Helmfile. Useful in templating if you have a helmfile per environment or customer and don't want to copy the same label to each release
commonLabels:
  project: {{requiredEnv "fdj-tomcat"}}
  env: {{requiredEnv "ref_slug"}}
releases:
- name: hello-world-{{requiredEnv "ref_slug"}}
  namespace: {{requiredEnv "pref-tom"}}{{requiredEnv "ref_slug"}}
  labels:
    app: hello-world
    component: tomcat
  createNamespace: {{dev}}
  chart: gdp/tomcat-gdp
  version: 9.2.12-0.0.28
  missingFileHandler: Error
  values:
  - components/hello-world/hello-world-values.yml.gotmpl
  - components/hello-world/values.yaml
