environments:
  default:
    values:
      - &common
        project: hello-world
  devtodev:
    values:
      - <<: *common
        dnsBase: paas-jeux.dev.fdj.fr
        clusterDomain: dtd-vit.local
  int:
    values:
      - <<: *common
        dnsBase: paas-jeux.vit.int.fdj.fr
        clusterDomain: jhp-vit.local      
